import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LoCiFile",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-backgroundLight dark:bg-backgroundDark text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden`}
      >
        <Navbar />
        <main className="mt-16">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
